### GENERAL SETTINGS ###

# Site settings
title: ADI FAHMI
description: "Adi Fahmi's Personal Site."
analytics: UA-91950225-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://adifahmi.me"
author: Adi Fahmi
disqus_shortname: adifahmi

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://fb.com/adifahmii
  - title: twitter
    url: https://twitter.com/adifahmii
  - title: instagram
    url: https://instagram.com/adifahmii
  - title: linkedin
    url: https://www.linkedin.com/in/adifahmii
  - title: google-plus
    url: https://plus.google.com/+MuhAdiFahmi
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Rawalumbu,
    - 17116, Bekasi,
    - Indonesia.
email: adifahmi379@gmail.com
tel: +62 838 768 682 38

# SEARCH ENGINE KNOW HTTPS
url: https://adifahmi.me
enforce_ssl: adifahmi.me

# JEKYLL SITEMAP
gems:
  - jekyll-sitemap

### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
# members:
#   - name: Mark Webber
#     position: CEO
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team01.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Paul Jameson
#     position: Lead Designer
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team02.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Laura Sommers
#     position: Lead Developer
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team03.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
#   - name: Martin Blunt
#     position: Marketing
#     text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#     img: team04.jpg
#     social:
#       - title: envelope #use for email address
#         url: mailto:name@domain.com
#       - title: twitter
#         url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text. Shown in footer on every page and also separately on Home and Contact page.
about: "This site is hosted on GitHub, theme is Solid. A Bootstrap theme for Jekyll. Â© Adi Fahmi 2017."
about_author: "<del>A fresh graduate</del> Currently a Software Engineer with some works and projects experience. Used to autodidact, willing to learn and making fast adaption to work as a team."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
